services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - crdbdata:/cockroach/cockroach-data
    restart: unless-stopped

volumes:
  crdbdata:
