services:
  ferretdb:
    image: ferretdb/ferretdb:latest
    ports:
      - "27017:27017"
    environment:
      FERRETDB_POSTGRESQL_URL: "postgres://postgres:postgres@postgres:5432/ferretdb"
    restart: unless-stopped
