services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "mariadb"
      MARIADB_DATABASE: "mydb"
    volumes:
      - mariadbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadbdata:
